package com.oss2.translationclient.listener;

import com.oss2.translationclient.annotation.TranslatableField;
import com.oss2.translationclient.client.TranslationClient;
import com.oss2.translationclient.util.SpringContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jakarta.persistence.PostPersist;
import jakarta.persistence.PostUpdate;
import jakarta.persistence.PreRemove;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import java.lang.reflect.Field;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import jakarta.persistence.EntityManager;

public class TranslationEntityListener {
    private static final Logger log = LoggerFactory.getLogger(TranslationEntityListener.class);

    @PrePersist
    @PreUpdate
    public void captureTranslations(Object entity) {
        try {
            Field[] fields = entity.getClass().getDeclaredFields();
            for (Field field : fields) {
                if (field.isAnnotationPresent(TranslatableField.class)) {
                    field.setAccessible(true);
                    Object value = field.get(entity);

                    if (value != null && value instanceof String) {
                        String strValue = (String) value;
                        String prefix = entity.getClass().getSimpleName().toLowerCase() + ".";

                        if (!strValue.startsWith(prefix)) {
                            String originalText = strValue;
                            String entityId = extractId(entity);
                            String messageKey = prefix + entityId + "." + field.getName().toLowerCase();

                            TranslationClient translationClient = SpringContext.getBean(TranslationClient.class);
                            boolean registered = false;

                            if (translationClient != null) {
                                try {
                                    log.info("Registering translation key '{}' for content: {}", messageKey,
                                            originalText);
                                    translationClient.registerTranslation(
                                            new TranslationClient.TranslationRegistrationRequest(messageKey, "en",
                                                    originalText));
                                    registered = true;
                                } catch (Exception e) {
                                    log.error("Failed to register translation for key " + messageKey, e);
                                    // If registration fails, we still want to save the original text
                                }
                            } else {
                                log.warn("TranslationClient bean not available via SpringContext.");
                            }

                            if (registered) {
                                field.set(entity, messageKey);
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            log.error("Error during TranslationEntityListener processing:", e);
        }
    }

    // In case an entity ID is purely generated by the database (like
    // auto-increment),
    // the ID is only available after persist. We could catch it here to update
    // translations,
    // but the @PrePersist approach above is required because we need to mutate the
    // entity's field
    // BEFORE the SQL INSERT statement happens.
    // Since ARMAS entities like Organization use predefined String IDs (e.g. UUIDs
    // created on the frontend or backend),
    // PrePersist is sufficient.

    @PreRemove
    public void removeTranslations(Object entity) {
        try {
            String prefix = entity.getClass().getSimpleName().toLowerCase() + "." + extractId(entity) + ".";
            TranslationClient translationClient = SpringContext.getBean(TranslationClient.class);
            if (translationClient != null) {
                CompletableFuture.runAsync(() -> {
                    try {
                        translationClient.deleteTranslationsByPrefix(prefix);
                        log.info("Deleted orphaned translations for prefix: {}", prefix);
                    } catch (Exception e) {
                        log.error("Failed to delete translations for prefix " + prefix, e);
                    }
                });
            }
        } catch (Exception e) {
            log.error("Error during @PreRemove processing:", e);
        }
    }

    private String extractId(Object entity) {
        try {
            Field idField = entity.getClass().getDeclaredField("id");
            idField.setAccessible(true);
            Object idVal = idField.get(entity);
            if (idVal != null && !idVal.toString().isEmpty()) {
                return idVal.toString();
            }
        } catch (Exception e) {
            log.warn("Entity {} does not have an 'id' field.", entity.getClass().getSimpleName());
        }

        // Try searching for any field annotated with @Id if 'id' field name isn't found
        try {
            for (Field field : entity.getClass().getDeclaredFields()) {
                if (field.isAnnotationPresent(jakarta.persistence.Id.class)) {
                    field.setAccessible(true);
                    Object idVal = field.get(entity);
                    if (idVal != null)
                        return idVal.toString();
                }
            }
        } catch (Exception e) {
        }

        // Fallback random ID if entity has no ID yet.
        return UUID.randomUUID().toString().substring(0, 8);
    }
}
